language: cpp
sudo: required
compiler:
  - gcc

before_install:
  - git clone https://github.com/nigels-com/glew.git && cd glew
  - cd build
  - cmake ./cmake
  - make
  - sudo make install
  - cd ../..
  - git clone https://github.com/glfw/glfw.git && cd glfw
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..

script:
  - mkdir build && cd build
  - cmake .. && cmake --build .

after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - pip install sphinx breathe sphinx_rtd_theme
  - cd docs && make html
  - git commit -m "Commit from Travis CI for build $TRAVIS_BUILD_NUMBER ."
  - git push --quiet https://$GH_TOKEN@github.com/tatsy/OpenGLCourseJP.git gh-pages:gh-pages 2> /dev/null
  - cd ..
  - git commit -m "Commit from Travis CI for build $TRAVIS_BUILD_NUMBER ."
  - git push --quiet https://$GH_TOKEN@github.com/tatsy/OpenGLCourseJP.git master:master 2> /dev/null

branches:
  only:
    - master
    - development

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
